
export const pickCharacterName = (type: string): string => {
  const nameList = characterNames[type];
  return nameList[Math.floor(Math.random() * nameList.length)];
}

const characterNames: {[type: string]: string[]} = {
  barbarian: [
    "Throm",
    "Gorg the Cleaver",
    "Kragu",
    "Brak Smacker",
    "Hulgor",
    "Brakka",
    "Ugg the Wall",
    "Vrok",
    "Mugor Woodchopper",
    "Grond",
    "Krell",
    "Darg the Blunt",
    "Thrum Bloodaxe",
    "Bolg",
    "Gromm",
    "Skarl",
    "Urk Facebreaker",
    "Brok",
    "Rorg",
    "Mug the Mountain",
    "Karg",
    "Blorg",
    "Grog Ironhide",
    "Thrag Bonesplit",
    "Glunk",
    "Zogg",
    "Krom the Bear",
    "Durg Skullmash",
    "Borgh",
    "Trog",
    "Skrum Skullcrag",
    "Harg",
    "Vrak",
    "Grump Blackaxe",
    "Skar Stonefist",
    "Zrak",
    "Orok the Loud",
    "Brag",
    "Gruk Skullcrack",
    "Brogon",
    "Mulg",
    "Kroll the Thick",
    "Gronk",
    "Thrakk",
    "Urk the Tree",
    "Dragg",
    "Worg",
    "Brum Shieldbiter",
    "Zulg",
    "Karg Ironbone",
    "Skar",
    "Grak",
    "Mugg Bloodspill",
    "Drok",
    "Vrul Woodcarver",
    "Barg",
    "Hulgin",
    "Grom Bonebreaker",
    "Throk",
    "Kragg",
    "Glunk the Anvil",
    "Brok Axehand",
    "Zorg",
    "Krul",
    "Gorg the Heavy",
    "Skar Woodsplitter",
    "Rokk",
    "Thrum",
    "Brak the Rock",
    "Mugor",
    "Vrok Fleshrender",
    "Darg",
    "Grog",
    "Krell Ironfist",
    "Hulgor the Wild",
    "Brog",
    "Zrakk",
    "Orok Bonecarver",
    "Grond the Cudgel",
    "Krom",
    "Blorg Meatgrind",
    "Thrag",
    "Skar Axechopper",
    "Durg",
    "Mulg the Stump",
    "Vrakga",
    "Skrum",
    "Gruk the Great",
    "Trog Shieldbreak",
    "Brum",
    "Worg the Savage",
    "Harg Woodhewer",
    "Zulg Skullmasher",
    "Vrul",
    "Kroll",
    "Gronk the Beast",
    "Dragg Fleshcutter",
    "Thrakk Bloodmar",
    "Rorg Axehammer",
    "Urk"
  ],
  witch: [
    "Morwenna",
    "Baba Vesta",
    "Haxen",
    "Sycorax",
    "Vendra the Vile",
    "Malice",
    "Zalika",
    "Griselda",
    "Hecate the Pale",
    "Belladonna",
    "Kaelia Nightshade",
    "Vespera",
    "Zola",
    "Nyx the Weaver",
    "Myra",
    "Bricia",
    "Kallista",
    "Lilith the Grim",
    "Zexia",
    "Morrigan",
    "Grixis",
    "Dahlia Bane",
    "Vexen",
    "Sybil",
    "Voldra",
    "Morgana the Dark",
    "Selene",
    "Zadia Hex",
    "Drusilla",
    "Nox",
    "Ursula",
    "Scylla the Black",
    "Braya",
    "Vilecia",
    "Kendra Raven",
    "Kyna",
    "Zephra",
    "Mala the Crone",
    "Drusa",
    "Ravena",
    "Zalera",
    "Skarlett",
    "Gorgona",
    "Brena the Blind",
    "Viconia",
    "Thana",
    "Sabrina",
    "Malvina Crow",
    "Xendra",
    "Zora",
    "Tenebra",
    "Klyta",
    "Gretel the Hag",
    "Morg",
    "Valeska",
    "Zorina Witch",
    "Nesta",
    "Krella",
    "Lyra the Leech",
    "Banshee",
    "Hesta",
    "Zoxia Shadow",
    "Vexia",
    "Nesta Moon",
    "Draga",
    "Myrka",
    "Sycorax the Sly",
    "Zulma",
    "Gola",
    "Vesper Hex",
    "Runa",
    "Gilda",
    "Malakor",
    "Kaelia the Old",
    "Breda",
    "Viconia Bane",
    "Xalaria",
    "Zindra",
    "Tenebra the Hag",
    "Kora",
    "Selene Shadow",
    "Mala",
    "Dahlia",
    "Nyx Raven",
    "Ursula Black",
    "Zalika Night",
    "Griselda Dark",
    "Voldra the Vile",
    "Bricia Crow",
    "Zola the Grim",
    "Haxen Leech",
    "Kallista Moon",
    "Sybil the Blind",
    "Drusilla Vile",
    "Belladonna Hag",
    "Morwenna Pale",
    "Vendra Raven",
    "Zadia Night",
    "Myrka the Black",
    "Scylla"
  ],
  ranger: [
    "Aveline",
    "Lyra Swift",
    "Artemis",
    "Sariel",
    "Kaelen the Swift",
    "Ffion",
    "Sylvia",
    "Rowan Wood",
    "Bryn Falcon",
    "Tala",
    "Kira Arrow",
    "Nesta",
    "Maeve the Keen",
    "Shayle",
    "Taryn",
    "Faelar Wood",
    "Kira",
    "Lyra the Hawk",
    "Anya",
    "Nesta Bow",
    "Sariel Hawk",
    "Elowen",
    "Bryn",
    "Tala Tracker",
    "Artemis Hawk",
    "Kaelen Swift",
    "Aveline Bow",
    "Maeve Falcon",
    "Sylvia Wood",
    "Rowan",
    "Ffion Tracker",
    "Shayle Falcon",
    "Taryn Arrow",
    "Faelar Swift",
    "Anya Wood",
    "Kira Falcon",
    "Lyra Tracker",
    "Nesta Swift",
    "Sariel Wood",
    "Elowen Arrow",
    "Bryn Tracker",
    "Tala Falcon",
    "Artemis Swift",
    "Kaelen Wood",
    "Aveline Hawk",
    "Maeve Arrow",
    "Sylvia Tracker",
    "Rowan Falcon",
    "Ffion Swift",
    "Shayle Wood",
    "Taryn Tracker",
    "Faelar Arrow",
    "Anya Falcon",
    "Kira Tracker",
    "Lyra Arrow",
    "Nesta Hawk",
    "Sariel Swift",
    "Elowen Falcon",
    "Bryn Wood",
    "Tala Arrow",
    "Artemis Wood",
    "Kaelen Hawk",
    "Aveline Swift",
    "Maeve Wood",
    "Sylvia Falcon",
    "Rowan Arrow",
    "Ffion Hawk",
    "Shayle Swift",
    "Taryn Wood",
    "Faelar Hawk",
    "Anya Tracker",
    "Kira Swift",
    "Lyra Wood",
    "Nesta Falcon",
    "Sariel Arrow",
    "Elowen Hawk",
    "Bryn Swift",
    "Tala Wood",
    "Artemis Arrow",
    "Kaelen Falcon",
    "Aveline Wood",
    "Maeve Swift",
    "Sylvia Arrow",
    "Rowan Hawk",
    "Ffion Wood",
    "Shayle Arrow",
    "Taryn Hawk",
    "Faelar Falcon",
    "Anya Arrow",
    "Kira Hawk",
    "Lyra Falcon",
    "Nesta Tracker",
    "Sariel Falcon",
    "Elowen Swift",
    "Bryn Arrow",
    "Tala Swift",
    "Artemis Falcon",
    "Kaelen Arrow",
    "Aveline Tracker",
    "Maeve"
  ],
  mage: [
    "Thoradin",
    "Balin Flame",
    "Gimli Frost",
    "Dwalin Mend",
    "Gloin the Healer",
    "Bofur Sparks",
    "Thrain Rime",
    "Thorin",
    "Balin the Kind",
    "Gimli Blaze",
    "Dwalin Chill",
    "Gloin Cure",
    "Bofur the Pyre",
    "Thrain Glaze",
    "Thorin Mend",
    "Balin the White",
    "Gimli Ignite",
    "Dwalin Frost",
    "Gloin the Warm",
    "Bofur Ice",
    "Thrain",
    "Thorin Blaze",
    "Balin Chill",
    "Gimli Mend",
    "Dwalin Spark",
    "Gloin Rime",
    "Bofur the Kind",
    "Thrain Flare",
    "Thorin Glaze",
    "Balin",
    "Gimli the Warm",
    "Dwalin Pyre",
    "Gloin Frost",
    "Bofur Mend",
    "Thrain Spark",
    "Thorin Chill",
    "Balin Ignite",
    "Gimli Rime",
    "Dwalin the Kind",
    "Gloin Flare",
    "Bofur Glaze",
    "Thrain Blaze",
    "Thorin Frost",
    "Balin Mend",
    "Gimli Spark",
    "Dwalin Rime",
    "Gloin Blaze",
    "Bofur Chill",
    "Thrain Pyre",
    "Thorin Rime",
    "Balin Spark",
    "Gimli Pyre",
    "Dwalin Flare",
    "Gloin Ice",
    "Bofur Blaze",
    "Thrain Chill",
    "Thorin Flare",
    "Balin Rime",
    "Gimli Flare",
    "Dwalin Ignite",
    "Gloin Pyre",
    "Bofur Flare",
    "Thrain Frost",
    "Thorin Spark",
    "Balin Flare",
    "Gimli Chill",
    "Dwalin Ice",
    "Gloin Spark",
    "Bofur Frost",
    "Thrain Rime",
    "Thorin Pyre",
    "Balin Ice",
    "Gimli Glaze",
    "Dwalin Glaze",
    "Gloin Chill",
    "Bofur Rime",
    "Thrain Ice",
    "Thorin Ice",
    "Balin Pyre",
    "Gimli Ice",
    "Dwalin Blaze",
    "Gloin Ignite",
    "Bofur Ignite",
    "Thrain Flare",
    "Thorin Ignite",
    "Balin Glaze",
    "Gimli Ignite",
    "Dwalin Pyre",
    "Gloin Rime",
    "Bofur Spark",
    "Thrain Spark",
    "Thorin Rime",
    "Balin Flare",
    "Gimli Blaze",
    "Dwalin Frost",
    "Gloin Flare",
    "Bofur Chill",
    "Thrain Frost",
    "Thorin Chill"
  ],
};