import { AllMonsterState } from '../store/types';

export const monsters1: AllMonsterState = {
  monsters: [
    {
      id: "m1",
      type: "rat",
      location: 6,
      health: 5,
    },
    {
      id: "m2",
      type: "spider",
      location: 7,
      health: 5,
    },
    {
      id: "m3",
      type: "spider",
      location: 7,
      health: 5,
    },
    {
      id: "m4",
      type: "rat",
      location: 9,
      health: 5,
    },
    {
      id: "m5",
      type: "rat",
      location: 11,
      health: 5,
    },
    {
      id: "m6",
      type: "rat",
      location: 11,
      health: 5,
    },
    {
      id: "m7",
      type: "spider",
      location: 13,
      health: 5,
    },
    {
      id: "m8",
      type: "spider",
      location: 13,
      health: 5,
    },
    {
      id: "m9",
      type: "spider",
      location: 14,
      health: 5,
    },
    {
      id: "m10",
      type: "spider",
      location: 16,
      health: 5,
    },
    {
      id: "m11",
      type: "spider",
      location: 16,
      health: 5,
    },
    {
      id: "m12",
      type: "spider",
      location: 18,
      health: 5,
    },
    {
      id: "m13",
      type: "spider",
      location: 18,
      health: 5,
    },
    {
      id: "m14",
      type: "spider",
      location: 18,
      health: 5,
    },
    {
      id: "m15",
      type: "spider",
      location: 20,
      health: 5,
    },
    {
      id: "m16",
      type: "spider",
      location: 20,
      health: 5,
    },
    {
      id: "m17",
      type: "spider",
      location: 20,
      health: 5,
    },
    {
      id: "m18",
      type: "rat",
      location: 1,
      health: 5,
    },
    {
      id: "m19",
      type: "rat",
      location: 1,
      health: 5,
    },
    {
      id: "m20",
      type: "rat",
      location: 3,
      health: 5,
    },
    {
      id: "m21",
      type: "rat",
      location: 3,
      health: 5,
    },
    {
      id: "m22",
      type: "rat",
      location: 3,
      health: 5,
    },
    {
      id: "m23",
      type: "goblin",
      location: 26,
      health: 8,
    },
    {
      id: "m24",
      type: "goblin",
      location: 26,
      health: 8,
    },
    {
      id: "m25",
      type: "spider",
      location: 30,
      health: 5,
    },
    {
      id: "m26",
      type: "spider",
      location: 30,
      health: 5,
    },
    {
      id: "m27",
      type: "spider",
      location: 30,
      health: 5,
    },
    {
      id: "m28",
      type: "goblin",
      location: 36,
      health: 8,
    },
    {
      id: "m29",
      type: "goblin",
      location: 36,
      health: 8,
    },
    {
      id: "m30",
      type: "goblin",
      location: 36,
      health: 8,
    },
    {
      id: "m31",
      type: "rat",
      location: 40,
      health: 5,
    },
    {
      id: "m32",
      type: "rat",
      location: 40,
      health: 5,
    },
    {
      id: "m33",
      type: "spider",
      location: 48,
      health: 5,
    },
    {
      id: "m34",
      type: "spider",
      location: 48,
      health: 5,
    },
    {
      id: "m35",
      type: "spider",
      location: 48,
      health: 5,
    },
    {
      id: "m36",
      type: "goblin",
      location: 51,
      health: 8,
    },
    {
      id: "m37",
      type: "goblin",
      location: 51,
      health: 8,
    },
    {
      id: "m38",
      type: "goblin",
      location: 51,
      health: 8,
    },
    {
      id: "m39",
      type: "spider",
      location: 52,
      health: 5,
    },
    {
      id: "m40",
      type: "spider",
      location: 52,
      health: 5,
    },
    {
      id: "m41",
      type: "spider",
      location: 52,
      health: 5,
    },
    {
      id: "m42",
      type: "spider",
      location: 52,
      health: 5,
    },
    {
      id: "m43",
      type: "goblin",
      location: 53,
      health: 8,
    },
    {
      id: "m44",
      type: "goblin",
      location: 53,
      health: 8,
    },
    {
      id: "m45",
      type: "goblin",
      location: 53,
      health: 8,
    },
    {
      id: "m46",
      type: "spider",
      location: 61,
      health: 5,
    },
    {
      id: "m47",
      type: "spider",
      location: 61,
      health: 5,
    },
    {
      id: "m48",
      type: "spider",
      location: 61,
      health: 5,
    },
    {
      id: "m49",
      type: "spider",
      location: 61,
      health: 5,
    },
    {
      id: "m50",
      type: "goblin",
      location: 69,
      health: 8,
    },
    {
      id: "m51",
      type: "goblin",
      location: 69,
      health: 8,
    },
    {
      id: "m52",
      type: "goblin",
      location: 69,
      health: 8,
    },
    {
      id: "m53",
      type: "goblin",
      location: 69,
      health: 8,
    },
    {
      id: "m54",
      type: "spider",
      location: 70,
      health: 5,
    },
    {
      id: "m55",
      type: "spider",
      location: 70,
      health: 5,
    },
    {
      id: "m56",
      type: "spider",
      location: 70,
      health: 5,
    },
    {
      id: "m57",
      type: "spider",
      location: 70,
      health: 5,
    },
    {
      id: "m58",
      type: "spider",
      location: 70,
      health: 5,
    },
    {
      id: "m59",
      type: "goblin",
      location: 73,
      health: 8,
    },
    {
      id: "m60",
      type: "goblin",
      location: 73,
      health: 8,
    },
    {
      id: "m61",
      type: "goblin",
      location: 73,
      health: 8,
    },
    {
      id: "m62",
      type: "goblin",
      location: 73,
      health: 8,
    },
    {
      id: "m63",
      type: "goblin",
      location: 73,
      health: 8,
    },
    {
      id: "m64",
      type: "goblin",
      location: 80,
      health: 8,
    },
    {
      id: "m65",
      type: "goblin",
      location: 80,
      health: 8,
    },
    {
      id: "m66",
      type: "goblin",
      location: 80,
      health: 8,
    },
    {
      id: "m67",
      type: "goblin",
      location: 80,
      health: 8,
    },
    {
      id: "m68",
      type: "goblin",
      location: 85,
      health: 8,
    },
    {
      id: "m69",
      type: "goblin",
      location: 85,
      health: 8,
    },
    {
      id: "m70",
      type: "goblin",
      location: 85,
      health: 8,
    },
    {
      id: "m71",
      type: "goblin",
      location: 85,
      health: 8,
    },
    {
      id: "m72",
      type: "goblin",
      location: 85,
      health: 8,
    },
    {
      id: "m73",
      type: "spider",
      location: 97,
      health: 5,
    },
    {
      id: "m74",
      type: "spider",
      location: 97,
      health: 5,
    },
    {
      id: "m75",
      type: "spider",
      location: 97,
      health: 5,
    },
    {
      id: "m76",
      type: "spider",
      location: 97,
      health: 5,
    },
    {
      id: "m77",
      type: "spider",
      location: 97,
      health: 5,
    },
    {
      id: "m78",
      type: "goblin",
      location: 100,
      health: 8,
    },
    {
      id: "m79",
      type: "goblin",
      location: 100,
      health: 8,
    },
    {
      id: "m80",
      type: "goblin",
      location: 100,
      health: 8,
    },
    {
      id: "m81",
      type: "goblin",
      location: 100,
      health: 8,
    },
    {
      id: "m82",
      type: "goblin",
      location: 100,
      health: 8,
    },
    {
      id: "m83",
      type: "goblin",
      location: 100,
      health: 8,
    },
    {
      id: "m84",
      type: "goblin",
      location: 101,
      health: 8,
    },
    {
      id: "m85",
      type: "goblin",
      location: 101,
      health: 8,
    },
    {
      id: "m86",
      type: "goblin",
      location: 101,
      health: 8,
    },
    {
      id: "m87",
      type: "goblin",
      location: 101,
      health: 8,
    },
    {
      id: "m88",
      type: "goblin",
      location: 101,
      health: 8,
    },
    {
      id: "m89",
      type: "goblin",
      location: 101,
      health: 8,
    },
    {
      id: "m90",
      type: "spider",
      location: 106,
      health: 5,
    },
    {
      id: "m91",
      type: "spider",
      location: 106,
      health: 5,
    },
    {
      id: "m92",
      type: "spider",
      location: 106,
      health: 5,
    },
    {
      id: "m93",
      type: "spider",
      location: 106,
      health: 5,
    },
    {
      id: "m94",
      type: "spider",
      location: 106,
      health: 5,
    },
    {
      id: "m95",
      type: "goblin",
      location: 112,
      health: 8,
    },
    {
      id: "m96",
      type: "goblin",
      location: 112,
      health: 8,
    },
    {
      id: "m97",
      type: "goblin",
      location: 112,
      health: 8,
    },
    {
      id: "m98",
      type: "goblin",
      location: 112,
      health: 8,
    },
    {
      id: "m99",
      type: "goblin",
      location: 112,
      health: 8,
    },
    {
      id: "m100",
      type: "goblin",
      location: 136,
      health: 8,
    },
    {
      id: "m101",
      type: "goblin",
      location: 136,
      health: 8,
    },
    {
      id: "m102",
      type: "goblin",
      location: 136,
      health: 8,
    },
    {
      id: "m103",
      type: "goblin",
      location: 136,
      health: 8,
    },
    {
      id: "m104",
      type: "goblin",
      location: 136,
      health: 8,
    },
    {
      id: "m105",
      type: "goblin",
      location: 136,
      health: 8,
    },
    {
      id: "m106",
      type: "goblin",
      location: 138,
      health: 8,
    },
    {
      id: "m107",
      type: "goblin",
      location: 138,
      health: 8,
    },
    {
      id: "m108",
      type: "goblin",
      location: 138,
      health: 8,
    },
    {
      id: "m109",
      type: "goblin",
      location: 138,
      health: 8,
    },
    {
      id: "m110",
      type: "goblin",
      location: 138,
      health: 8,
    },
    {
      id: "m111",
      type: "goblin",
      location: 138,
      health: 8,
    },
    {
      id: "m112",
      type: "goblin",
      location: 139,
      health: 8,
    },
    {
      id: "m113",
      type: "goblin",
      location: 139,
      health: 8,
    },
    {
      id: "m114",
      type: "goblin",
      location: 139,
      health: 8,
    },
    {
      id: "m115",
      type: "goblin",
      location: 139,
      health: 8,
    },
    {
      id: "m116",
      type: "goblin",
      location: 139,
      health: 8,
    },
    {
      id: "m117",
      type: "goblin",
      location: 139,
      health: 8,
    },
    {
      id: "m118",
      type: "goblin",
      location: 139,
      health: 8,
    },
    {
      id: "m119",
      type: "goblin",
      location: 151,
      health: 8,
    },
    {
      id: "m120",
      type: "goblin",
      location: 151,
      health: 8,
    },
    {
      id: "m121",
      type: "goblin",
      location: 151,
      health: 8,
    },
    {
      id: "m122",
      type: "goblin",
      location: 151,
      health: 8,
    },
    {
      id: "m123",
      type: "goblin",
      location: 151,
      health: 8,
    },
    {
      id: "m124",
      type: "goblin",
      location: 151,
      health: 8,
    },
    {
      id: "m125",
      type: "goblin",
      location: 156,
      health: 8,
    },
    {
      id: "m126",
      type: "goblin",
      location: 156,
      health: 8,
    },
    {
      id: "m127",
      type: "goblin",
      location: 156,
      health: 8,
    },
    {
      id: "m128",
      type: "goblin",
      location: 156,
      health: 8,
    },
    {
      id: "m129",
      type: "goblin",
      location: 156,
      health: 8,
    },
    {
      id: "m130",
      type: "goblin",
      location: 156,
      health: 8,
    },
    {
      id: "m131",
      type: "goblin",
      location: 156,
      health: 8,
    },
    {
      id: "m132",
      type: "goblin",
      location: 160,
      health: 8,
    },
    {
      id: "m133",
      type: "goblin",
      location: 160,
      health: 8,
    },
    {
      id: "m134",
      type: "goblin",
      location: 160,
      health: 8,
    },
    {
      id: "m135",
      type: "goblin",
      location: 160,
      health: 8,
    },
    {
      id: "m136",
      type: "goblin",
      location: 160,
      health: 8,
    },
    {
      id: "m137",
      type: "goblin",
      location: 160,
      health: 8,
    },
    {
      id: "m138",
      type: "goblin",
      location: 160,
      health: 8,
    },
    {
      id: "m139",
      type: "goblin",
      location: 168,
      health: 8,
    },
    {
      id: "m140",
      type: "goblin",
      location: 168,
      health: 8,
    },
    {
      id: "m141",
      type: "goblin",
      location: 168,
      health: 8,
    },
    {
      id: "m142",
      type: "goblin",
      location: 168,
      health: 8,
    },
    {
      id: "m143",
      type: "goblin",
      location: 168,
      health: 8,
    },
    {
      id: "m144",
      type: "goblin",
      location: 168,
      health: 8,
    },
    {
      id: "m145",
      type: "goblin",
      location: 168,
      health: 8,
    },
    {
      id: "m146",
      type: "spider",
      location: 178,
      health: 5,
    },
    {
      id: "m147",
      type: "spider",
      location: 178,
      health: 5,
    },
    {
      id: "m148",
      type: "spider",
      location: 178,
      health: 5,
    },
    {
      id: "m149",
      type: "spider",
      location: 178,
      health: 5,
    },
    {
      id: "m150",
      type: "spider",
      location: 178,
      health: 5,
    },
    {
      id: "m151",
      type: "spider",
      location: 178,
      health: 5,
    },
    {
      id: "m152",
      type: "spider",
      location: 178,
      health: 5,
    },
    {
      id: "m153",
      type: "spider",
      location: 178,
      health: 5,
    },
    {
      id: "m154",
      type: "goblin",
      location: 179,
      health: 8,
    },
    {
      id: "m155",
      type: "goblin",
      location: 179,
      health: 8,
    },
    {
      id: "m156",
      type: "goblin",
      location: 179,
      health: 8,
    },
    {
      id: "m157",
      type: "goblin",
      location: 179,
      health: 8,
    },
    {
      id: "m158",
      type: "goblin",
      location: 179,
      health: 8,
    },
    {
      id: "m159",
      type: "goblin",
      location: 179,
      health: 8,
    },
    {
      id: "m160",
      type: "goblin",
      location: 179,
      health: 8,
    },
    {
      id: "m161",
      type: "goblin",
      location: 179,
      health: 8,
    },
    {
      id: "m162",
      type: "goblin",
      location: 180,
      health: 8,
    },
    {
      id: "m163",
      type: "goblin",
      location: 180,
      health: 8,
    },
    {
      id: "m164",
      type: "goblin",
      location: 180,
      health: 8,
    },
    {
      id: "m165",
      type: "goblin",
      location: 180,
      health: 8,
    },
    {
      id: "m166",
      type: "goblin",
      location: 180,
      health: 8,
    },
    {
      id: "m167",
      type: "goblin",
      location: 180,
      health: 8,
    },
    {
      id: "m168",
      type: "goblin",
      location: 180,
      health: 8,
    },
    {
      id: "m169",
      type: "goblin",
      location: 180,
      health: 8,
    },
    {
      id: "m170",
      type: "goblin",
      location: 192,
      health: 8,
    },
    {
      id: "m171",
      type: "goblin",
      location: 192,
      health: 8,
    },
    {
      id: "m172",
      type: "goblin",
      location: 192,
      health: 8,
    },
    {
      id: "m173",
      type: "goblin",
      location: 192,
      health: 8,
    },
    {
      id: "m174",
      type: "goblin",
      location: 192,
      health: 8,
    },
    {
      id: "m175",
      type: "goblin",
      location: 192,
      health: 8,
    },
    {
      id: "m176",
      type: "goblin",
      location: 192,
      health: 8,
    },
    {
      id: "m177",
      type: "goblin",
      location: 192,
      health: 8,
    },
    {
      id: "m178",
      type: "goblin",
      location: 199,
      health: 8,
    },
    {
      id: "m179",
      type: "goblin",
      location: 199,
      health: 8,
    },
    {
      id: "m180",
      type: "goblin",
      location: 199,
      health: 8,
    },
    {
      id: "m181",
      type: "goblin",
      location: 199,
      health: 8,
    },
    {
      id: "m182",
      type: "goblin",
      location: 199,
      health: 8,
    },
    {
      id: "m183",
      type: "goblin",
      location: 199,
      health: 8,
    },
    {
      id: "m184",
      type: "goblin",
      location: 199,
      health: 8,
    },
    {
      id: "m185",
      type: "goblin",
      location: 199,
      health: 8,
    },
    {
      id: "m186",
      type: "goblin",
      location: 202,
      health: 8,
    },
    {
      id: "m187",
      type: "goblin",
      location: 202,
      health: 8,
    },
    {
      id: "m188",
      type: "goblin",
      location: 202,
      health: 8,
    },
    {
      id: "m189",
      type: "goblin",
      location: 202,
      health: 8,
    },
    {
      id: "m190",
      type: "goblin",
      location: 202,
      health: 8,
    },
    {
      id: "m191",
      type: "goblin",
      location: 202,
      health: 8,
    },
    {
      id: "m192",
      type: "goblin",
      location: 202,
      health: 8,
    },
    {
      id: "m193",
      type: "goblin",
      location: 202,
      health: 8,
    },
    {
      id: "m194",
      type: "goblin",
      location: 202,
      health: 8,
    },
    {
      id: "m195",
      type: "goblin",
      location: 206,
      health: 8,
    },
    {
      id: "m196",
      type: "goblin",
      location: 206,
      health: 8,
    },
    {
      id: "m197",
      type: "goblin",
      location: 206,
      health: 8,
    },
    {
      id: "m198",
      type: "goblin",
      location: 206,
      health: 8,
    },
    {
      id: "m199",
      type: "goblin",
      location: 206,
      health: 8,
    },
    {
      id: "m200",
      type: "goblin",
      location: 206,
      health: 8,
    },
    {
      id: "m201",
      type: "goblin",
      location: 206,
      health: 8,
    },
    {
      id: "m202",
      type: "goblin",
      location: 206,
      health: 8,
    },
    {
      id: "m203",
      type: "skeleton",
      location: 214,
      health: 20,
    },
    {
      id: "m204",
      type: "skeleton",
      location: 214,
      health: 20,
    },
    {
      id: "m205",
      type: "skeleton",
      location: 214,
      health: 20,
    },
    {
      id: "m206",
      type: "skeleton",
      location: 214,
      health: 20,
    },
    {
      id: "m207",
      type: "skeleton",
      location: 214,
      health: 20,
    },
    {
      id: "m208",
      type: "skeleton",
      location: 214,
      health: 20,
    },
    {
      id: "m209",
      type: "skeleton",
      location: 214,
      health: 20,
    },
    {
      id: "m210",
      type: "skeleton",
      location: 214,
      health: 20,
    },
    {
      id: "m211",
      type: "skeleton",
      location: 216,
      health: 20,
    },
    {
      id: "m212",
      type: "skeleton",
      location: 216,
      health: 20,
    },
    {
      id: "m213",
      type: "skeleton",
      location: 216,
      health: 20,
    },
    {
      id: "m214",
      type: "skeleton",
      location: 216,
      health: 20,
    },
    {
      id: "m215",
      type: "skeleton",
      location: 216,
      health: 20,
    },
    {
      id: "m216",
      type: "skeleton",
      location: 216,
      health: 20,
    },
    {
      id: "m217",
      type: "skeleton",
      location: 216,
      health: 20,
    },
    {
      id: "m218",
      type: "skeleton",
      location: 216,
      health: 20,
    },
    {
      id: "m219",
      type: "skeleton",
      location: 216,
      health: 20,
    },
    {
      id: "m220",
      type: "skeleton",
      location: 217,
      health: 20,
    },
    {
      id: "m221",
      type: "skeleton",
      location: 217,
      health: 20,
    },
    {
      id: "m222",
      type: "skeleton",
      location: 217,
      health: 20,
    },
    {
      id: "m223",
      type: "skeleton",
      location: 217,
      health: 20,
    },
    {
      id: "m224",
      type: "skeleton",
      location: 217,
      health: 20,
    },
    {
      id: "m225",
      type: "skeleton",
      location: 217,
      health: 20,
    },
    {
      id: "m226",
      type: "skeleton",
      location: 217,
      health: 20,
    },
    {
      id: "m227",
      type: "skeleton",
      location: 217,
      health: 20,
    },
    {
      id: "m228",
      type: "skeleton",
      location: 217,
      health: 20,
    },
    {
      id: "m229",
      type: "skeleton",
      location: 217,
      health: 20,
    },
    {
      id: "m230",
      type: "skeleton",
      location: 218,
      health: 20,
    },
    {
      id: "m231",
      type: "skeleton",
      location: 218,
      health: 20,
    },
    {
      id: "m232",
      type: "skeleton",
      location: 218,
      health: 20,
    },
    {
      id: "m233",
      type: "skeleton",
      location: 218,
      health: 20,
    },
    {
      id: "m234",
      type: "skeleton",
      location: 218,
      health: 20,
    },
    {
      id: "m235",
      type: "skeleton",
      location: 218,
      health: 20,
    },
    {
      id: "m236",
      type: "skeleton",
      location: 218,
      health: 20,
    },
    {
      id: "m237",
      type: "skeleton",
      location: 218,
      health: 20,
    },
    {
      id: "m238",
      type: "skeleton",
      location: 219,
      health: 20,
    },
    {
      id: "m239",
      type: "skeleton",
      location: 219,
      health: 20,
    },
    {
      id: "m240",
      type: "skeleton",
      location: 219,
      health: 20,
    },
    {
      id: "m241",
      type: "skeleton",
      location: 219,
      health: 20,
    },
    {
      id: "m242",
      type: "skeleton",
      location: 219,
      health: 20,
    },
    {
      id: "m243",
      type: "skeleton",
      location: 219,
      health: 20,
    },
    {
      id: "m244",
      type: "skeleton",
      location: 219,
      health: 20,
    },
    {
      id: "m245",
      type: "skeleton",
      location: 219,
      health: 20,
    },
    {
      id: "m246",
      type: "skeleton",
      location: 219,
      health: 20,
    },
    {
      id: "m247",
      type: "skeleton",
      location: 222,
      health: 20,
    },
    {
      id: "m248",
      type: "skeleton",
      location: 222,
      health: 20,
    },
    {
      id: "m249",
      type: "skeleton",
      location: 222,
      health: 20,
    },
    {
      id: "m250",
      type: "skeleton",
      location: 222,
      health: 20,
    },
    {
      id: "m251",
      type: "skeleton",
      location: 222,
      health: 20,
    },
    {
      id: "m252",
      type: "skeleton",
      location: 222,
      health: 20,
    },
    {
      id: "m253",
      type: "skeleton",
      location: 222,
      health: 20,
    },
    {
      id: "m254",
      type: "skeleton",
      location: 222,
      health: 20,
    },
    {
      id: "m255",
      type: "skeleton",
      location: 222,
      health: 20,
    },
    {
      id: "m256",
      type: "skeleton",
      location: 224,
      health: 20,
    },
    {
      id: "m257",
      type: "skeleton",
      location: 224,
      health: 20,
    },
    {
      id: "m258",
      type: "skeleton",
      location: 224,
      health: 20,
    },
    {
      id: "m259",
      type: "skeleton",
      location: 224,
      health: 20,
    },
    {
      id: "m260",
      type: "skeleton",
      location: 224,
      health: 20,
    },
    {
      id: "m261",
      type: "skeleton",
      location: 224,
      health: 20,
    },
    {
      id: "m262",
      type: "skeleton",
      location: 224,
      health: 20,
    },
    {
      id: "m263",
      type: "skeleton",
      location: 224,
      health: 20,
    },
    {
      id: "m264",
      type: "skeleton",
      location: 224,
      health: 20,
    },
    {
      id: "m265",
      type: "skeleton",
      location: 224,
      health: 20,
    },
    {
      id: "m266",
      type: "skeleton",
      location: 226,
      health: 20,
    },
    {
      id: "m267",
      type: "skeleton",
      location: 226,
      health: 20,
    },
    {
      id: "m268",
      type: "skeleton",
      location: 226,
      health: 20,
    },
    {
      id: "m269",
      type: "skeleton",
      location: 226,
      health: 20,
    },
    {
      id: "m270",
      type: "skeleton",
      location: 226,
      health: 20,
    },
    {
      id: "m271",
      type: "skeleton",
      location: 226,
      health: 20,
    },
    {
      id: "m272",
      type: "skeleton",
      location: 226,
      health: 20,
    },
    {
      id: "m273",
      type: "skeleton",
      location: 226,
      health: 20,
    },
    {
      id: "m274",
      type: "skeleton",
      location: 226,
      health: 20,
    },
    {
      id: "m275",
      type: "skeleton",
      location: 226,
      health: 20,
    },
    {
      id: "m276",
      type: "goblin",
      location: 238,
      health: 8,
    },
    {
      id: "m277",
      type: "goblin",
      location: 238,
      health: 8,
    },
    {
      id: "m278",
      type: "goblin",
      location: 238,
      health: 8,
    },
    {
      id: "m279",
      type: "goblin",
      location: 238,
      health: 8,
    },
    {
      id: "m280",
      type: "goblin",
      location: 238,
      health: 8,
    },
    {
      id: "m281",
      type: "goblin",
      location: 238,
      health: 8,
    },
    {
      id: "m282",
      type: "goblin",
      location: 238,
      health: 8,
    },
    {
      id: "m283",
      type: "goblin",
      location: 238,
      health: 8,
    },
    {
      id: "m284",
      type: "goblin",
      location: 238,
      health: 8,
    },
    {
      id: "m285",
      type: "goblin",
      location: 240,
      health: 8,
    },
    {
      id: "m286",
      type: "goblin",
      location: 240,
      health: 8,
    },
    {
      id: "m287",
      type: "goblin",
      location: 240,
      health: 8,
    },
    {
      id: "m288",
      type: "goblin",
      location: 240,
      health: 8,
    },
    {
      id: "m289",
      type: "goblin",
      location: 240,
      health: 8,
    },
    {
      id: "m290",
      type: "goblin",
      location: 240,
      health: 8,
    },
    {
      id: "m291",
      type: "goblin",
      location: 240,
      health: 8,
    },
    {
      id: "m292",
      type: "goblin",
      location: 240,
      health: 8,
    },
    {
      id: "m293",
      type: "goblin",
      location: 240,
      health: 8,
    },
    {
      id: "m294",
      type: "goblin",
      location: 240,
      health: 8,
    },
  ]
};
