import { AllLocationsState } from '../../store/types';

export const monsters: AllLocationsState = {
  items: [],
  monsters: [
    {
      id: "m1",
      type: "rat",
      location: 1,
      health: 5,
    },
    {
      id: "m2",
      type: "rat",
      location: 1,
      health: 5,
    },
    {
      id: "m3",
      type: "spider",
      location: 1,
      health: 5,
    },
    {
      id: "m4",
      type: "rat",
      location: 2,
      health: 5,
    },
    {
      id: "m5",
      type: "snake",
      location: 2,
      health: 8,
    },
    {
      id: "m6",
      type: "spider",
      location: 3,
      health: 5,
    },
    {
      id: "m7",
      type: "spider",
      location: 3,
      health: 5,
    },
    {
      id: "m8",
      type: "goblin",
      location: 4,
      health: 8,
    },
    {
      id: "m9",
      type: "rat",
      location: 6,
      health: 5,
    },
    {
      id: "m10",
      type: "spider",
      location: 7,
      health: 5,
    },
    {
      id: "m11",
      type: "snake",
      location: 8,
      health: 8,
    },
    {
      id: "m12",
      type: "rat",
      location: 9,
      health: 5,
    },
    {
      id: "m13",
      type: "rat",
      location: 11,
      health: 5,
    },
    {
      id: "m14",
      type: "snake",
      location: 12,
      health: 8,
    },
    {
      id: "m15",
      type: "spider",
      location: 13,
      health: 5,
    },
    {
      id: "m16",
      type: "snake",
      location: 15,
      health: 8,
    },
    {
      id: "m17",
      type: "spider",
      location: 16,
      health: 5,
    },
    {
      id: "m18",
      type: "snake",
      location: 17,
      health: 8,
    },
    {
      id: "m19",
      type: "snake",
      location: 17,
      health: 8,
    },
    {
      id: "m20",
      type: "spider",
      location: 18,
      health: 5,
    },
    {
      id: "m21",
      type: "snake",
      location: 18,
      health: 8,
    },
    {
      id: "m22",
      type: "goblin",
      location: 19,
      health: 8,
    },
    {
      id: "m23",
      type: "goblin",
      location: 20,
      health: 8,
    },
    {
      id: "m24",
      type: "goblin",
      location: 20,
      health: 8,
    },
    {
      id: "m25",
      type: "goblin",
      location: 25,
      health: 8,
    },
    {
      id: "m26",
      type: "goblin",
      location: 26,
      health: 8,
    },
    {
      id: "m27",
      type: "goblin",
      location: 26,
      health: 8,
    },
    {
      id: "m28",
      type: "spider",
      location: 27,
      health: 5,
    },
    {
      id: "m29",
      type: "snake",
      location: 29,
      health: 8,
    },
    {
      id: "m30",
      type: "spider",
      location: 30,
      health: 5,
    },
    {
      id: "m31",
      type: "rat",
      location: 31,
      health: 5,
    },
    {
      id: "m32",
      type: "snake",
      location: 32,
      health: 8,
    },
    {
      id: "m33",
      type: "spider",
      location: 33,
      health: 5,
    },
    {
      id: "m34",
      type: "rat",
      location: 35,
      health: 5,
    },
    {
      id: "m35",
      type: "spider",
      location: 35,
      health: 5,
    },
    {
      id: "m36",
      type: "goblin",
      location: 36,
      health: 8,
    },
    {
      id: "m37",
      type: "goblin",
      location: 36,
      health: 8,
    },
    {
      id: "m38",
      type: "spider",
      location: 37,
      health: 5,
    },
    {
      id: "m39",
      type: "goblin",
      location: 38,
      health: 8,
    },
    {
      id: "m40",
      type: "goblin",
      location: 38,
      health: 8,
    },
    {
      id: "m41",
      type: "spider",
      location: 39,
      health: 5,
    },
    {
      id: "m42",
      type: "spider",
      location: 40,
      health: 5,
    },
    {
      id: "m43",
      type: "spider",
      location: 40,
      health: 5,
    },
    {
      id: "m44",
      type: "goblin",
      location: 41,
      health: 8,
    },
    {
      id: "m45",
      type: "snake",
      location: 41,
      health: 8,
    },
    {
      id: "m46",
      type: "goblin",
      location: 42,
      health: 8,
    },
    {
      id: "m47",
      type: "goblin",
      location: 42,
      health: 8,
    },
    {
      id: "m48",
      type: "spider",
      location: 43,
      health: 5,
    },
    {
      id: "m49",
      type: "spider",
      location: 44,
      health: 5,
    },
    {
      id: "m50",
      type: "goblin",
      location: 44,
      health: 8,
    },
    {
      id: "m51",
      type: "snake",
      location: 45,
      health: 8,
    },
    {
      id: "m52",
      type: "spider",
      location: 47,
      health: 5,
    },
    {
      id: "m53",
      type: "spider",
      location: 48,
      health: 5,
    },
    {
      id: "m54",
      type: "spider",
      location: 48,
      health: 5,
    },
    {
      id: "m55",
      type: "rat",
      location: 49,
      health: 5,
    },
    {
      id: "m56",
      type: "spider",
      location: 50,
      health: 5,
    },
    {
      id: "m57",
      type: "spider",
      location: 50,
      health: 5,
    },
    {
      id: "m58",
      type: "spider",
      location: 51,
      health: 5,
    },
    {
      id: "m59",
      type: "snake",
      location: 51,
      health: 8,
    },
    {
      id: "m60",
      type: "spider",
      location: 52,
      health: 5,
    },
    {
      id: "m61",
      type: "goblin",
      location: 52,
      health: 8,
    },
    {
      id: "m62",
      type: "goblin",
      location: 53,
      health: 8,
    },
    {
      id: "m63",
      type: "goblin",
      location: 53,
      health: 8,
    },
    {
      id: "m64",
      type: "goblin",
      location: 54,
      health: 8,
    },
    {
      id: "m65",
      type: "snake",
      location: 56,
      health: 8,
    },
    {
      id: "m66",
      type: "snake",
      location: 61,
      health: 8,
    },
    {
      id: "m67",
      type: "snake",
      location: 61,
      health: 8,
    },
    {
      id: "m68",
      type: "spider",
      location: 62,
      health: 5,
    },
    {
      id: "m69",
      type: "snake",
      location: 62,
      health: 8,
    },
    {
      id: "m70",
      type: "snake",
      location: 63,
      health: 8,
    },
    {
      id: "m71",
      type: "goblin",
      location: 64,
      health: 8,
    },
    {
      id: "m72",
      type: "snake",
      location: 65,
      health: 8,
    },
    {
      id: "m73",
      type: "rat",
      location: 67,
      health: 5,
    },
    {
      id: "m74",
      type: "goblin",
      location: 68,
      health: 8,
    },
    {
      id: "m75",
      type: "goblin",
      location: 69,
      health: 8,
    },
    {
      id: "m76",
      type: "spider",
      location: 69,
      health: 5,
    },
    {
      id: "m77",
      type: "spider",
      location: 70,
      health: 5,
    },
    {
      id: "m78",
      type: "spider",
      location: 70,
      health: 5,
    },
    {
      id: "m79",
      type: "snake",
      location: 71,
      health: 8,
    },
    {
      id: "m80",
      type: "goblin",
      location: 73,
      health: 8,
    },
    {
      id: "m81",
      type: "orc",
      location: 73,
      health: 14,
    },
    {
      id: "m82",
      type: "orc",
      location: 74,
      health: 14,
    },
    {
      id: "m83",
      type: "orc",
      location: 74,
      health: 14,
    },
    {
      id: "m84",
      type: "goblin",
      location: 75,
      health: 8,
    },
    {
      id: "m85",
      type: "spider",
      location: 76,
      health: 5,
    },
    {
      id: "m86",
      type: "goblin",
      location: 76,
      health: 8,
    },
    {
      id: "m87",
      type: "goblin",
      location: 77,
      health: 8,
    },
    {
      id: "m88",
      type: "snake",
      location: 78,
      health: 8,
    },
    {
      id: "m89",
      type: "snake",
      location: 80,
      health: 8,
    },
    {
      id: "m90",
      type: "spider",
      location: 80,
      health: 5,
    },
    {
      id: "m91",
      type: "goblin",
      location: 81,
      health: 8,
    },
    {
      id: "m92",
      type: "spider",
      location: 82,
      health: 5,
    },
    {
      id: "m93",
      type: "goblin",
      location: 83,
      health: 8,
    },
    {
      id: "m94",
      type: "orc",
      location: 83,
      health: 14,
    },
    {
      id: "m95",
      type: "goblin",
      location: 84,
      health: 8,
    },
    {
      id: "m96",
      type: "orc",
      location: 85,
      health: 14,
    },
    {
      id: "m97",
      type: "orc",
      location: 85,
      health: 14,
    },
    {
      id: "m98",
      type: "goblin",
      location: 85,
      health: 8,
    },
    {
      id: "m99",
      type: "spider",
      location: 86,
      health: 5,
    },
    {
      id: "m100",
      type: "goblin",
      location: 87,
      health: 8,
    },
    {
      id: "m101",
      type: "goblin",
      location: 87,
      health: 8,
    },
    {
      id: "m102",
      type: "snake",
      location: 88,
      health: 8,
    },
    {
      id: "m103",
      type: "spider",
      location: 89,
      health: 5,
    },
    {
      id: "m104",
      type: "goblin",
      location: 92,
      health: 8,
    },
    {
      id: "m105",
      type: "snake",
      location: 94,
      health: 8,
    },
    {
      id: "m106",
      type: "spider",
      location: 95,
      health: 5,
    },
    {
      id: "m107",
      type: "snake",
      location: 96,
      health: 8,
    },
    {
      id: "m108",
      type: "snake",
      location: 96,
      health: 8,
    },
    {
      id: "m109",
      type: "goblin",
      location: 97,
      health: 8,
    },
    {
      id: "m110",
      type: "goblin",
      location: 97,
      health: 8,
    },
    {
      id: "m111",
      type: "snake",
      location: 98,
      health: 8,
    },
    {
      id: "m112",
      type: "goblin",
      location: 99,
      health: 8,
    },
    {
      id: "m113",
      type: "snake",
      location: 100,
      health: 8,
    },
    {
      id: "m114",
      type: "snake",
      location: 100,
      health: 8,
    },
    {
      id: "m115",
      type: "orc",
      location: 101,
      health: 14,
    },
    {
      id: "m116",
      type: "orc",
      location: 101,
      health: 14,
    },
    {
      id: "m117",
      type: "goblin",
      location: 101,
      health: 8,
    },
    {
      id: "m118",
      type: "snake",
      location: 102,
      health: 8,
    },
    {
      id: "m119",
      type: "goblin",
      location: 102,
      health: 8,
    },
    {
      id: "m120",
      type: "snake",
      location: 103,
      health: 8,
    },
    {
      id: "m121",
      type: "goblin",
      location: 104,
      health: 8,
    },
    {
      id: "m122",
      type: "goblin",
      location: 105,
      health: 8,
    },
    {
      id: "m123",
      type: "spider",
      location: 106,
      health: 5,
    },
    {
      id: "m124",
      type: "snake",
      location: 108,
      health: 8,
    },
    {
      id: "m125",
      type: "spider",
      location: 109,
      health: 5,
    },
    {
      id: "m126",
      type: "spider",
      location: 111,
      health: 5,
    },
    {
      id: "m127",
      type: "goblin",
      location: 112,
      health: 8,
    },
    {
      id: "m128",
      type: "snake",
      location: 113,
      health: 8,
    },
    {
      id: "m129",
      type: "rat",
      location: 114,
      health: 5,
    },
    {
      id: "m130",
      type: "goblin",
      location: 116,
      health: 8,
    },
    {
      id: "m131",
      type: "goblin",
      location: 116,
      health: 8,
    },
    {
      id: "m132",
      type: "spider",
      location: 117,
      health: 5,
    },
    {
      id: "m133",
      type: "spider",
      location: 117,
      health: 5,
    },
    {
      id: "m134",
      type: "goblin",
      location: 120,
      health: 8,
    },
    {
      id: "m135",
      type: "orc",
      location: 120,
      health: 14,
    },
    {
      id: "m136",
      type: "snake",
      location: 124,
      health: 8,
    },
    {
      id: "m137",
      type: "goblin",
      location: 126,
      health: 8,
    },
    {
      id: "m138",
      type: "snake",
      location: 128,
      health: 8,
    },
    {
      id: "m139",
      type: "goblin",
      location: 129,
      health: 8,
    },
    {
      id: "m140",
      type: "spider",
      location: 131,
      health: 5,
    },
    {
      id: "m141",
      type: "snake",
      location: 133,
      health: 8,
    },
    {
      id: "m142",
      type: "goblin",
      location: 134,
      health: 8,
    },
    {
      id: "m143",
      type: "orc",
      location: 136,
      health: 14,
    },
    {
      id: "m144",
      type: "orc",
      location: 136,
      health: 14,
    },
    {
      id: "m145",
      type: "goblin",
      location: 137,
      health: 8,
    },
    {
      id: "m146",
      type: "orc",
      location: 137,
      health: 14,
    },
    {
      id: "m147",
      type: "orc",
      location: 138,
      health: 14,
    },
    {
      id: "m148",
      type: "goblin",
      location: 138,
      health: 8,
    },
    {
      id: "m149",
      type: "orc",
      location: 139,
      health: 14,
    },
    {
      id: "m150",
      type: "orc",
      location: 139,
      health: 14,
    },
    {
      id: "m151",
      type: "orc",
      location: 140,
      health: 14,
    },
    {
      id: "m152",
      type: "goblin",
      location: 140,
      health: 8,
    },
    {
      id: "m153",
      type: "orc",
      location: 141,
      health: 14,
    },
    {
      id: "m154",
      type: "orc",
      location: 141,
      health: 14,
    },
    {
      id: "m155",
      type: "orc",
      location: 142,
      health: 14,
    },
    {
      id: "m156",
      type: "goblin",
      location: 142,
      health: 8,
    },
    {
      id: "m157",
      type: "spider",
      location: 143,
      health: 5,
    },
    {
      id: "m158",
      type: "orc",
      location: 143,
      health: 14,
    },
    {
      id: "m159",
      type: "goblin",
      location: 144,
      health: 8,
    },
    {
      id: "m160",
      type: "spider",
      location: 146,
      health: 5,
    },
    {
      id: "m161",
      type: "snake",
      location: 147,
      health: 8,
    },
    {
      id: "m162",
      type: "goblin",
      location: 148,
      health: 8,
    },
    {
      id: "m163",
      type: "orc",
      location: 149,
      health: 14,
    },
    {
      id: "m164",
      type: "orc",
      location: 149,
      health: 14,
    },
    {
      id: "m165",
      type: "orc",
      location: 150,
      health: 14,
    },
    {
      id: "m166",
      type: "orc",
      location: 150,
      health: 14,
    },
    {
      id: "m167",
      type: "orc",
      location: 151,
      health: 14,
    },
    {
      id: "m168",
      type: "orc",
      location: 151,
      health: 14,
    },
    {
      id: "m169",
      type: "orc",
      location: 152,
      health: 14,
    },
    {
      id: "m170",
      type: "orc",
      location: 152,
      health: 14,
    },
    {
      id: "m171",
      type: "orc",
      location: 153,
      health: 14,
    },
    {
      id: "m172",
      type: "orc",
      location: 153,
      health: 14,
    },
    {
      id: "m173",
      type: "goblin",
      location: 154,
      health: 8,
    },
    {
      id: "m174",
      type: "orc",
      location: 156,
      health: 14,
    },
    {
      id: "m175",
      type: "orc",
      location: 156,
      health: 14,
    },
    {
      id: "m176",
      type: "orc",
      location: 157,
      health: 14,
    },
    {
      id: "m177",
      type: "orc",
      location: 157,
      health: 14,
    },
    {
      id: "m178",
      type: "orc",
      location: 158,
      health: 14,
    },
    {
      id: "m179",
      type: "orc",
      location: 158,
      health: 14,
    },
    {
      id: "m180",
      type: "orc",
      location: 159,
      health: 14,
    },
    {
      id: "m181",
      type: "orc",
      location: 159,
      health: 14,
    },
    {
      id: "m182",
      type: "ogre",
      location: 159,
      health: 22,
    },
    {
      id: "m183",
      type: "orc",
      location: 160,
      health: 14,
    },
    {
      id: "m184",
      type: "orc",
      location: 160,
      health: 14,
    },
    {
      id: "m185",
      type: "orc",
      location: 161,
      health: 14,
    },
    {
      id: "m186",
      type: "ogre",
      location: 161,
      health: 22,
    },
    {
      id: "m187",
      type: "orc",
      location: 162,
      health: 14,
    },
    {
      id: "m188",
      type: "orc",
      location: 162,
      health: 14,
    },
    {
      id: "m189",
      type: "orc",
      location: 163,
      health: 14,
    },
    {
      id: "m190",
      type: "ogre",
      location: 163,
      health: 22,
    },
    {
      id: "m191",
      type: "orc",
      location: 164,
      health: 14,
    },
    {
      id: "m192",
      type: "orc",
      location: 164,
      health: 14,
    },
    {
      id: "m193",
      type: "orc",
      location: 165,
      health: 14,
    },
    {
      id: "m194",
      type: "orc",
      location: 166,
      health: 14,
    },
    {
      id: "m195",
      type: "ogre",
      location: 166,
      health: 22,
    },
    {
      id: "m196",
      type: "orc",
      location: 167,
      health: 14,
    },
    {
      id: "m197",
      type: "orc",
      location: 167,
      health: 14,
    },
    {
      id: "m198",
      type: "orc",
      location: 168,
      health: 14,
    },
    {
      id: "m199",
      type: "ogre",
      location: 168,
      health: 22,
    },
    {
      id: "m200",
      type: "orc",
      location: 169,
      health: 14,
    },
    {
      id: "m201",
      type: "orc",
      location: 169,
      health: 14,
    },
    {
      id: "m202",
      type: "orc",
      location: 170,
      health: 14,
    },
    {
      id: "m203",
      type: "orc",
      location: 170,
      health: 14,
    },
    {
      id: "m204",
      type: "skeleton",
      location: 171,
      health: 16,
    },
    {
      id: "m205",
      type: "skeleton",
      location: 171,
      health: 16,
    },
    {
      id: "m206",
      type: "goblin",
      location: 172,
      health: 8,
    },
    {
      id: "m207",
      type: "spider",
      location: 174,
      health: 5,
    },
    {
      id: "m208",
      type: "skeleton",
      location: 175,
      health: 16,
    },
    {
      id: "m209",
      type: "skeleton",
      location: 175,
      health: 16,
    },
    {
      id: "m210",
      type: "goblin",
      location: 176,
      health: 8,
    },
    {
      id: "m211",
      type: "skeleton",
      location: 177,
      health: 16,
    },
    {
      id: "m212",
      type: "skeleton",
      location: 177,
      health: 16,
    },
    {
      id: "m213",
      type: "goblin",
      location: 178,
      health: 8,
    },
    {
      id: "m214",
      type: "spider",
      location: 178,
      health: 5,
    },
    {
      id: "m215",
      type: "spider",
      location: 179,
      health: 5,
    },
    {
      id: "m216",
      type: "goblin",
      location: 179,
      health: 8,
    },
    {
      id: "m217",
      type: "spider",
      location: 180,
      health: 5,
    },
    {
      id: "m218",
      type: "skeleton",
      location: 181,
      health: 16,
    },
    {
      id: "m219",
      type: "skeleton",
      location: 181,
      health: 16,
    },
    {
      id: "m220",
      type: "skeleton",
      location: 182,
      health: 16,
    },
    {
      id: "m221",
      type: "skeleton",
      location: 182,
      health: 16,
    },
    {
      id: "m222",
      type: "skeleton",
      location: 183,
      health: 16,
    },
    {
      id: "m223",
      type: "skeleton",
      location: 183,
      health: 16,
    },
    {
      id: "m224",
      type: "skeleton",
      location: 184,
      health: 16,
    },
    {
      id: "m225",
      type: "skeleton",
      location: 184,
      health: 16,
    },
    {
      id: "m226",
      type: "skeleton",
      location: 184,
      health: 16,
    },
    {
      id: "m227",
      type: "skeleton",
      location: 185,
      health: 16,
    },
    {
      id: "m228",
      type: "skeleton",
      location: 185,
      health: 16,
    },
    {
      id: "m229",
      type: "skeleton",
      location: 186,
      health: 16,
    },
    {
      id: "m230",
      type: "skeleton",
      location: 186,
      health: 16,
    },
    {
      id: "m231",
      type: "skeleton",
      location: 187,
      health: 16,
    },
    {
      id: "m232",
      type: "skeleton",
      location: 187,
      health: 16,
    },
    {
      id: "m233",
      type: "skeleton",
      location: 188,
      health: 16,
    },
    {
      id: "m234",
      type: "skeleton",
      location: 188,
      health: 16,
    },
    {
      id: "m235",
      type: "orc",
      location: 189,
      health: 14,
    },
    {
      id: "m236",
      type: "goblin",
      location: 190,
      health: 8,
    },
    {
      id: "m237",
      type: "orc",
      location: 191,
      health: 14,
    },
    {
      id: "m238",
      type: "orc",
      location: 191,
      health: 14,
    },
    {
      id: "m239",
      type: "orc",
      location: 192,
      health: 14,
    },
    {
      id: "m240",
      type: "orc",
      location: 192,
      health: 14,
    },
    {
      id: "m241",
      type: "ogre",
      location: 192,
      health: 22,
    },
    {
      id: "m242",
      type: "orc",
      location: 193,
      health: 14,
    },
    {
      id: "m243",
      type: "orc",
      location: 193,
      health: 14,
    },
    {
      id: "m244",
      type: "ogre",
      location: 193,
      health: 22,
    },
    {
      id: "m245",
      type: "orc",
      location: 194,
      health: 14,
    },
    {
      id: "m246",
      type: "orc",
      location: 194,
      health: 14,
    },
    {
      id: "m247",
      type: "ogre",
      location: 194,
      health: 22,
    },
    {
      id: "m248",
      type: "orc",
      location: 195,
      health: 14,
    },
    {
      id: "m249",
      type: "orc",
      location: 195,
      health: 14,
    },
    {
      id: "m250",
      type: "ogre",
      location: 195,
      health: 22,
    },
    {
      id: "m251",
      type: "orc",
      location: 196,
      health: 14,
    },
    {
      id: "m252",
      type: "ogre",
      location: 196,
      health: 22,
    },
    {
      id: "m253",
      type: "orc",
      location: 197,
      health: 14,
    },
    {
      id: "m254",
      type: "orc",
      location: 197,
      health: 14,
    },
    {
      id: "m255",
      type: "ogre",
      location: 197,
      health: 22,
    },
    {
      id: "m256",
      type: "ogre",
      location: 197,
      health: 22,
    },
    {
      id: "m257",
      type: "orc",
      location: 198,
      health: 14,
    },
    {
      id: "m258",
      type: "ogre",
      location: 198,
      health: 22,
    },
    {
      id: "m259",
      type: "orc",
      location: 199,
      health: 14,
    },
    {
      id: "m260",
      type: "orc",
      location: 199,
      health: 14,
    },
    {
      id: "m261",
      type: "ogre",
      location: 199,
      health: 22,
    },
    {
      id: "m262",
      type: "ogre",
      location: 199,
      health: 22,
    },
    {
      id: "m263",
      type: "orc",
      location: 200,
      health: 14,
    },
    {
      id: "m264",
      type: "orc",
      location: 200,
      health: 14,
    },
    {
      id: "m265",
      type: "ogre",
      location: 200,
      health: 22,
    },
    {
      id: "m266",
      type: "orc",
      location: 201,
      health: 14,
    },
    {
      id: "m267",
      type: "orc",
      location: 201,
      health: 14,
    },
    {
      id: "m268",
      type: "ogre",
      location: 201,
      health: 22,
    },
    {
      id: "m269",
      type: "ogre",
      location: 201,
      health: 22,
    },
    {
      id: "m270",
      type: "ogre",
      location: 202,
      health: 22,
    },
    {
      id: "m271",
      type: "ogre",
      location: 202,
      health: 22,
    },
    {
      id: "m272",
      type: "ogre",
      location: 202,
      health: 22,
    },
    {
      id: "m273",
      type: "orc",
      location: 202,
      health: 14,
    },
    {
      id: "m274",
      type: "orc",
      location: 202,
      health: 14,
    },
    {
      id: "m275",
      type: "snake",
      location: 202,
      health: 8,
    },
    {
      id: "m276",
      type: "orc",
      location: 203,
      health: 14,
    },
    {
      id: "m277",
      type: "orc",
      location: 203,
      health: 14,
    },
    {
      id: "m278",
      type: "ogre",
      location: 203,
      health: 22,
    },
    {
      id: "m279",
      type: "orc",
      location: 204,
      health: 14,
    },
    {
      id: "m280",
      type: "orc",
      location: 204,
      health: 14,
    },
    {
      id: "m281",
      type: "ogre",
      location: 204,
      health: 22,
    },
    {
      id: "m282",
      type: "ogre",
      location: 204,
      health: 22,
    },
    {
      id: "m283",
      type: "orc",
      location: 205,
      health: 14,
    },
    {
      id: "m284",
      type: "ogre",
      location: 205,
      health: 22,
    },
    {
      id: "m285",
      type: "orc",
      location: 206,
      health: 14,
    },
    {
      id: "m286",
      type: "orc",
      location: 206,
      health: 14,
    },
    {
      id: "m287",
      type: "ogre",
      location: 206,
      health: 22,
    },
    {
      id: "m288",
      type: "ogre",
      location: 206,
      health: 22,
    },
    {
      id: "m289",
      type: "orc",
      location: 207,
      health: 14,
    },
    {
      id: "m290",
      type: "ogre",
      location: 207,
      health: 22,
    },
    {
      id: "m291",
      type: "orc",
      location: 208,
      health: 14,
    },
    {
      id: "m292",
      type: "orc",
      location: 208,
      health: 14,
    },
    {
      id: "m293",
      type: "ogre",
      location: 208,
      health: 22,
    },
    {
      id: "m294",
      type: "orc",
      location: 209,
      health: 14,
    },
    {
      id: "m295",
      type: "ogre",
      location: 209,
      health: 22,
    },
    {
      id: "m296",
      type: "orc",
      location: 210,
      health: 14,
    },
    {
      id: "m297",
      type: "orc",
      location: 211,
      health: 14,
    },
    {
      id: "m298",
      type: "orc",
      location: 212,
      health: 14,
    },
    {
      id: "m299",
      type: "orc",
      location: 213,
      health: 14,
    },
    {
      id: "m300",
      type: "skeleton",
      location: 214,
      health: 16,
    },
    {
      id: "m301",
      type: "skeleton",
      location: 214,
      health: 16,
    },
    {
      id: "m302",
      type: "orc",
      location: 215,
      health: 14,
    },
    {
      id: "m303",
      type: "orc",
      location: 216,
      health: 14,
    },
    {
      id: "m304",
      type: "skeleton",
      location: 217,
      health: 16,
    },
    {
      id: "m305",
      type: "orc",
      location: 218,
      health: 14,
    },
    {
      id: "m306",
      type: "orc",
      location: 219,
      health: 14,
    },
    {
      id: "m307",
      type: "orc",
      location: 220,
      health: 14,
    },
    {
      id: "m308",
      type: "orc",
      location: 221,
      health: 14,
    },
    {
      id: "m309",
      type: "orc",
      location: 222,
      health: 14,
    },
    {
      id: "m310",
      type: "orc",
      location: 223,
      health: 14,
    },
    {
      id: "m311",
      type: "ogre",
      location: 224,
      health: 22,
    },
    {
      id: "m312",
      type: "orc",
      location: 225,
      health: 14,
    },
    {
      id: "m313",
      type: "orc",
      location: 226,
      health: 14,
    },
    {
      id: "m314",
      type: "orc",
      location: 227,
      health: 14,
    },
    {
      id: "m315",
      type: "orc",
      location: 228,
      health: 14,
    },
    {
      id: "m316",
      type: "spider",
      location: 229,
      health: 5,
    },
    {
      id: "m317",
      type: "goblin",
      location: 230,
      health: 8,
    },
    {
      id: "m318",
      type: "goblin",
      location: 231,
      health: 8,
    },
    {
      id: "m319",
      type: "orc",
      location: 232,
      health: 14,
    },
    {
      id: "m320",
      type: "ogre",
      location: 232,
      health: 22,
    },
    {
      id: "m321",
      type: "orc",
      location: 233,
      health: 14,
    },
    {
      id: "m322",
      type: "orc",
      location: 233,
      health: 14,
    },
    {
      id: "m323",
      type: "ogre",
      location: 233,
      health: 22,
    },
    {
      id: "m324",
      type: "orc",
      location: 234,
      health: 14,
    },
    {
      id: "m325",
      type: "orc",
      location: 234,
      health: 14,
    },
    {
      id: "m326",
      type: "ogre",
      location: 234,
      health: 22,
    },
    {
      id: "m327",
      type: "orc",
      location: 235,
      health: 14,
    },
    {
      id: "m328",
      type: "orc",
      location: 235,
      health: 14,
    },
    {
      id: "m329",
      type: "ogre",
      location: 235,
      health: 22,
    },
    {
      id: "m330",
      type: "orc",
      location: 236,
      health: 14,
    },
    {
      id: "m331",
      type: "ogre",
      location: 236,
      health: 22,
    },
    {
      id: "m332",
      type: "orc",
      location: 237,
      health: 14,
    },
    {
      id: "m333",
      type: "orc",
      location: 237,
      health: 14,
    },
    {
      id: "m334",
      type: "ogre",
      location: 237,
      health: 22,
    },
    {
      id: "m335",
      type: "ogre",
      location: 237,
      health: 22,
    },
    {
      id: "m336",
      type: "orc",
      location: 238,
      health: 14,
    },
    {
      id: "m337",
      type: "orc",
      location: 238,
      health: 14,
    },
    {
      id: "m338",
      type: "ogre",
      location: 238,
      health: 22,
    },
    {
      id: "m339",
      type: "ogre",
      location: 238,
      health: 22,
    },
    {
      id: "m340",
      type: "orc",
      location: 239,
      health: 14,
    },
    {
      id: "m341",
      type: "orc",
      location: 239,
      health: 14,
    },
    {
      id: "m342",
      type: "ogre",
      location: 239,
      health: 22,
    },
    {
      id: "m343",
      type: "ogre",
      location: 239,
      health: 22,
    },
    {
      id: "m344",
      type: "ogre",
      location: 239,
      health: 22,
    },
    {
      id: "m345",
      type: "orc",
      location: 240,
      health: 14,
    },
    {
      id: "m346",
      type: "orc",
      location: 240,
      health: 14,
    },
    {
      id: "m347",
      type: "orc",
      location: 240,
      health: 14,
    },
    {
      id: "m348",
      type: "ogre",
      location: 240,
      health: 22,
    },
    {
      id: "m349",
      type: "ogre",
      location: 240,
      health: 22,
    },
  ]
};
