import { AllMonsterState } from '../../store/types';

export const monsters: AllMonsterState = {
  monsters: [
    {
      id: "m1",
      type: "rat",
      location: 1,
      health: 5,
    },
    {
      id: "m2",
      type: "snake",
      location: 1,
      health: 8,
    },
    {
      id: "m3",
      type: "rat",
      location: 2,
      health: 5,
    },
    {
      id: "m4",
      type: "rat",
      location: 3,
      health: 5,
    },
    {
      id: "m5",
      type: "spider",
      location: 3,
      health: 5,
    },
    {
      id: "m6",
      type: "rat",
      location: 4,
      health: 5,
    },
    {
      id: "m7",
      type: "snake",
      location: 6,
      health: 8,
    },
    {
      id: "m8",
      type: "spider",
      location: 7,
      health: 5,
    },
    {
      id: "m9",
      type: "rat",
      location: 8,
      health: 5,
    },
    {
      id: "m10",
      type: "rat",
      location: 9,
      health: 5,
    },
    {
      id: "m11",
      type: "spider",
      location: 12,
      health: 5,
    },
    {
      id: "m12",
      type: "spider",
      location: 13,
      health: 5,
    },
    {
      id: "m13",
      type: "snake",
      location: 14,
      health: 8,
    },
    {
      id: "m14",
      type: "spider",
      location: 16,
      health: 5,
    },
    {
      id: "m15",
      type: "snake",
      location: 17,
      health: 8,
    },
    {
      id: "m16",
      type: "snake",
      location: 18,
      health: 8,
    },
    {
      id: "m17",
      type: "spider",
      location: 20,
      health: 5,
    },
    {
      id: "m18",
      type: "goblin",
      location: 25,
      health: 8,
    },
    {
      id: "m19",
      type: "spider",
      location: 26,
      health: 5,
    },
    {
      id: "m20",
      type: "snake",
      location: 27,
      health: 8,
    },
    {
      id: "m21",
      type: "goblin",
      location: 27,
      health: 8,
    },
    {
      id: "m22",
      type: "rat",
      location: 28,
      health: 5,
    },
    {
      id: "m23",
      type: "spider",
      location: 30,
      health: 5,
    },
    {
      id: "m24",
      type: "snake",
      location: 33,
      health: 8,
    },
    {
      id: "m25",
      type: "goblin",
      location: 34,
      health: 8,
    },
    {
      id: "m26",
      type: "spider",
      location: 35,
      health: 5,
    },
    {
      id: "m27",
      type: "goblin",
      location: 35,
      health: 8,
    },
    {
      id: "m28",
      type: "spider",
      location: 36,
      health: 5,
    },
    {
      id: "m29",
      type: "goblin",
      location: 36,
      health: 8,
    },
    {
      id: "m30",
      type: "goblin",
      location: 37,
      health: 8,
    },
    {
      id: "m31",
      type: "spider",
      location: 38,
      health: 5,
    },
    {
      id: "m32",
      type: "goblin",
      location: 38,
      health: 8,
    },
    {
      id: "m33",
      type: "goblin",
      location: 39,
      health: 8,
    },
    {
      id: "m34",
      type: "goblin",
      location: 40,
      health: 8,
    },
    {
      id: "m35",
      type: "spider",
      location: 41,
      health: 5,
    },
    {
      id: "m36",
      type: "goblin",
      location: 42,
      health: 8,
    },
    {
      id: "m37",
      type: "goblin",
      location: 43,
      health: 8,
    },
    {
      id: "m38",
      type: "spider",
      location: 44,
      health: 5,
    },
    {
      id: "m39",
      type: "goblin",
      location: 44,
      health: 8,
    },
    {
      id: "m40",
      type: "goblin",
      location: 47,
      health: 8,
    },
    {
      id: "m41",
      type: "spider",
      location: 48,
      health: 5,
    },
    {
      id: "m42",
      type: "goblin",
      location: 48,
      health: 8,
    },
    {
      id: "m43",
      type: "spider",
      location: 50,
      health: 5,
    },
    {
      id: "m44",
      type: "goblin",
      location: 51,
      health: 8,
    },
    {
      id: "m45",
      type: "spider",
      location: 52,
      health: 5,
    },
    {
      id: "m46",
      type: "orc",
      location: 52,
      health: 14,
    },
    {
      id: "m47",
      type: "goblin",
      location: 53,
      health: 8,
    },
    {
      id: "m48",
      type: "snake",
      location: 61,
      health: 8,
    },
    {
      id: "m49",
      type: "goblin",
      location: 62,
      health: 8,
    },
    {
      id: "m50",
      type: "spider",
      location: 63,
      health: 5,
    },
    {
      id: "m51",
      type: "orc",
      location: 64,
      health: 14,
    },
    {
      id: "m52",
      type: "goblin",
      location: 69,
      health: 8,
    },
    {
      id: "m53",
      type: "spider",
      location: 70,
      health: 5,
    },
    {
      id: "m54",
      type: "orc",
      location: 70,
      health: 14,
    },
    {
      id: "m55",
      type: "goblin",
      location: 73,
      health: 8,
    },
    {
      id: "m56",
      type: "orc",
      location: 73,
      health: 14,
    },
    {
      id: "m57",
      type: "goblin",
      location: 74,
      health: 8,
    },
    {
      id: "m58",
      type: "spider",
      location: 75,
      health: 5,
    },
    {
      id: "m59",
      type: "goblin",
      location: 76,
      health: 8,
    },
    {
      id: "m60",
      type: "spider",
      location: 81,
      health: 5,
    },
    {
      id: "m61",
      type: "orc",
      location: 82,
      health: 14,
    },
    {
      id: "m62",
      type: "spider",
      location: 83,
      health: 5,
    },
    {
      id: "m63",
      type: "orc",
      location: 83,
      health: 14,
    },
    {
      id: "m64",
      type: "goblin",
      location: 84,
      health: 8,
    },
    {
      id: "m65",
      type: "orc",
      location: 85,
      health: 14,
    },
    {
      id: "m66",
      type: "spider",
      location: 85,
      health: 5,
    },
    {
      id: "m67",
      type: "goblin",
      location: 86,
      health: 8,
    },
    {
      id: "m68",
      type: "orc",
      location: 87,
      health: 14,
    },
    {
      id: "m69",
      type: "spider",
      location: 97,
      health: 5,
    },
    {
      id: "m70",
      type: "snake",
      location: 98,
      health: 8,
    },
    {
      id: "m71",
      type: "goblin",
      location: 99,
      health: 8,
    },
    {
      id: "m72",
      type: "spider",
      location: 100,
      health: 5,
    },
    {
      id: "m73",
      type: "orc",
      location: 101,
      health: 14,
    },
    {
      id: "m74",
      type: "ogre",
      location: 101,
      health: 22,
    },
    {
      id: "m75",
      type: "spider",
      location: 102,
      health: 5,
    },
    {
      id: "m76",
      type: "goblin",
      location: 106,
      health: 8,
    },
    {
      id: "m77",
      type: "spider",
      location: 111,
      health: 5,
    },
    {
      id: "m78",
      type: "goblin",
      location: 112,
      health: 8,
    },
    {
      id: "m79",
      type: "spider",
      location: 113,
      health: 5,
    },
    {
      id: "m80",
      type: "goblin",
      location: 116,
      health: 8,
    },
    {
      id: "m81",
      type: "orc",
      location: 117,
      health: 14,
    },
    {
      id: "m82",
      type: "orc",
      location: 120,
      health: 14,
    },
    {
      id: "m83",
      type: "ogre",
      location: 120,
      health: 22,
    },
    {
      id: "m84",
      type: "orc",
      location: 136,
      health: 14,
    },
    {
      id: "m85",
      type: "ogre",
      location: 136,
      health: 22,
    },
    {
      id: "m86",
      type: "goblin",
      location: 137,
      health: 8,
    },
    {
      id: "m87",
      type: "orc",
      location: 138,
      health: 14,
    },
    {
      id: "m88",
      type: "orc",
      location: 139,
      health: 14,
    },
    {
      id: "m89",
      type: "ogre",
      location: 139,
      health: 22,
    },
    {
      id: "m90",
      type: "goblin",
      location: 140,
      health: 8,
    },
    {
      id: "m91",
      type: "goblin",
      location: 141,
      health: 8,
    },
    {
      id: "m92",
      type: "orc",
      location: 142,
      health: 14,
    },
    {
      id: "m93",
      type: "spider",
      location: 143,
      health: 5,
    },
    {
      id: "m94",
      type: "spider",
      location: 146,
      health: 5,
    },
    {
      id: "m95",
      type: "goblin",
      location: 150,
      health: 8,
    },
    {
      id: "m96",
      type: "orc",
      location: 151,
      health: 14,
    },
    {
      id: "m97",
      type: "goblin",
      location: 152,
      health: 8,
    },
    {
      id: "m98",
      type: "orc",
      location: 153,
      health: 14,
    },
    {
      id: "m99",
      type: "orc",
      location: 156,
      health: 14,
    },
    {
      id: "m100",
      type: "orc",
      location: 157,
      health: 14,
    },
    {
      id: "m101",
      type: "ogre",
      location: 158,
      health: 22,
    },
    {
      id: "m102",
      type: "orc",
      location: 159,
      health: 14,
    },
    {
      id: "m103",
      type: "ogre",
      location: 159,
      health: 22,
    },
    {
      id: "m104",
      type: "spider",
      location: 160,
      health: 5,
    },
    {
      id: "m105",
      type: "orc",
      location: 161,
      health: 14,
    },
    {
      id: "m106",
      type: "orc",
      location: 162,
      health: 14,
    },
    {
      id: "m107",
      type: "ogre",
      location: 163,
      health: 22,
    },
    {
      id: "m108",
      type: "orc",
      location: 164,
      health: 14,
    },
    {
      id: "m109",
      type: "orc",
      location: 166,
      health: 14,
    },
    {
      id: "m110",
      type: "ogre",
      location: 167,
      health: 22,
    },
    {
      id: "m111",
      type: "orc",
      location: 168,
      health: 14,
    },
    {
      id: "m112",
      type: "ogre",
      location: 169,
      health: 22,
    },
    {
      id: "m113",
      type: "orc",
      location: 170,
      health: 14,
    },
    {
      id: "m114",
      type: "spider",
      location: 171,
      health: 5,
    },
    {
      id: "m115",
      type: "goblin",
      location: 178,
      health: 8,
    },
    {
      id: "m116",
      type: "spider",
      location: 179,
      health: 5,
    },
    {
      id: "m117",
      type: "goblin",
      location: 180,
      health: 8,
    },
    {
      id: "m118",
      type: "skeleton",
      location: 181,
      health: 16,
    },
    {
      id: "m119",
      type: "skeleton",
      location: 182,
      health: 16,
    },
    {
      id: "m120",
      type: "skeleton",
      location: 183,
      health: 16,
    },
    {
      id: "m121",
      type: "skeleton",
      location: 185,
      health: 16,
    },
    {
      id: "m122",
      type: "skeleton",
      location: 186,
      health: 16,
    },
    {
      id: "m123",
      type: "skeleton",
      location: 187,
      health: 16,
    },
    {
      id: "m124",
      type: "skeleton",
      location: 188,
      health: 16,
    },
    {
      id: "m125",
      type: "orc",
      location: 192,
      health: 14,
    },
    {
      id: "m126",
      type: "ogre",
      location: 192,
      health: 22,
    },
    {
      id: "m127",
      type: "orc",
      location: 193,
      health: 14,
    },
    {
      id: "m128",
      type: "orc",
      location: 194,
      health: 14,
    },
    {
      id: "m129",
      type: "ogre",
      location: 195,
      health: 22,
    },
    {
      id: "m130",
      type: "orc",
      location: 196,
      health: 14,
    },
    {
      id: "m131",
      type: "ogre",
      location: 197,
      health: 22,
    },
    {
      id: "m132",
      type: "orc",
      location: 198,
      health: 14,
    },
    {
      id: "m133",
      type: "ogre",
      location: 199,
      health: 22,
    },
    {
      id: "m134",
      type: "orc",
      location: 199,
      health: 14,
    },
    {
      id: "m135",
      type: "spider",
      location: 200,
      health: 5,
    },
    {
      id: "m136",
      type: "orc",
      location: 201,
      health: 14,
    },
    {
      id: "m137",
      type: "ogre",
      location: 201,
      health: 22,
    },
    {
      id: "m138",
      type: "ogre",
      location: 202,
      health: 22,
    },
    {
      id: "m139",
      type: "ogre",
      location: 202,
      health: 22,
    },
    {
      id: "m140",
      type: "orc",
      location: 202,
      health: 14,
    },
    {
      id: "m141",
      type: "orc",
      location: 202,
      health: 14,
    },
    {
      id: "m142",
      type: "ogre",
      location: 202,
      health: 22,
    },
    {
      id: "m143",
      type: "goblin",
      location: 202,
      health: 8,
    },
    {
      id: "m144",
      type: "orc",
      location: 203,
      health: 14,
    },
    {
      id: "m145",
      type: "ogre",
      location: 204,
      health: 22,
    },
    {
      id: "m146",
      type: "orc",
      location: 204,
      health: 14,
    },
    {
      id: "m147",
      type: "orc",
      location: 204,
      health: 14,
    },
    {
      id: "m148",
      type: "goblin",
      location: 204,
      health: 8,
    },
    {
      id: "m149",
      type: "orc",
      location: 205,
      health: 14,
    },
    {
      id: "m150",
      type: "ogre",
      location: 206,
      health: 22,
    },
    {
      id: "m151",
      type: "orc",
      location: 207,
      health: 14,
    },
    {
      id: "m152",
      type: "orc",
      location: 208,
      health: 14,
    },
    {
      id: "m153",
      type: "orc",
      location: 209,
      health: 14,
    },
    {
      id: "m154",
      type: "skeleton",
      location: 214,
      health: 16,
    },
    {
      id: "m155",
      type: "skeleton",
      location: 214,
      health: 16,
    },
    {
      id: "m156",
      type: "skeleton",
      location: 214,
      health: 16,
    },
    {
      id: "m157",
      type: "skeleton",
      location: 216,
      health: 16,
    },
    {
      id: "m158",
      type: "skeleton",
      location: 216,
      health: 16,
    },
    {
      id: "m159",
      type: "skeleton",
      location: 217,
      health: 16,
    },
    {
      id: "m160",
      type: "skeleton",
      location: 217,
      health: 16,
    },
    {
      id: "m161",
      type: "skeleton",
      location: 217,
      health: 16,
    },
    {
      id: "m162",
      type: "skeleton",
      location: 217,
      health: 16,
    },
    {
      id: "m163",
      type: "skeleton",
      location: 218,
      health: 16,
    },
    {
      id: "m164",
      type: "skeleton",
      location: 218,
      health: 16,
    },
    {
      id: "m165",
      type: "skeleton",
      location: 219,
      health: 16,
    },
    {
      id: "m166",
      type: "skeleton",
      location: 219,
      health: 16,
    },
    {
      id: "m167",
      type: "skeleton",
      location: 224,
      health: 16,
    },
    {
      id: "m168",
      type: "skeleton",
      location: 224,
      health: 16,
    },
    {
      id: "m169",
      type: "skeleton",
      location: 224,
      health: 16,
    },
    {
      id: "m170",
      type: "skeleton",
      location: 224,
      health: 16,
    },
    {
      id: "m171",
      type: "skeleton",
      location: 224,
      health: 16,
    },
    {
      id: "m172",
      type: "ogre",
      location: 232,
      health: 22,
    },
    {
      id: "m173",
      type: "orc",
      location: 233,
      health: 14,
    },
    {
      id: "m174",
      type: "ogre",
      location: 234,
      health: 22,
    },
    {
      id: "m175",
      type: "orc",
      location: 235,
      health: 14,
    },
    {
      id: "m176",
      type: "orc",
      location: 236,
      health: 14,
    },
    {
      id: "m177",
      type: "ogre",
      location: 237,
      health: 22,
    },
    {
      id: "m178",
      type: "orc",
      location: 237,
      health: 14,
    },
    {
      id: "m179",
      type: "ogre",
      location: 238,
      health: 22,
    },
    {
      id: "m180",
      type: "orc",
      location: 238,
      health: 14,
    },
    {
      id: "m181",
      type: "ogre",
      location: 239,
      health: 22,
    },
    {
      id: "m182",
      type: "orc",
      location: 239,
      health: 14,
    },
    {
      id: "m183",
      type: "ogre",
      location: 240,
      health: 22,
    },
    {
      id: "m184",
      type: "orc",
      location: 240,
      health: 14,
    },
  ]
};
