import type { Metadata } from "next";
import { lora } from '@/app/fonts';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${lora.className} antialiased`}>
      <body>{children}</body>
    </html>
  );
}
